"""autogenerated by genmsg_py from PoleSectionStamped.msg. Do not edit."""
import roslib.message
import struct

import geometry_msgs.msg
import pole_structure_mapper.msg
import std_msgs.msg

class PoleSectionStamped(roslib.message.Message):
  _md5sum = "88747806e74b0d7df3494990a375e399"
  _type = "pole_structure_mapper/PoleSectionStamped"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# Description…

Header header			# timestamp and frame_id
PoleSection pole
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: pole_structure_mapper/PoleSection
# Description…

geometry_msgs/Point base
geometry_msgs/Vector3 axis
float32 diameter		# m
float32 length			# m

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
"""
  __slots__ = ['header','pole']
  _slot_types = ['Header','pole_structure_mapper/PoleSection']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       header,pole
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(PoleSectionStamped, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      if self.pole is None:
        self.pole = pole_structure_mapper.msg.PoleSection()
    else:
      self.header = std_msgs.msg._Header.Header()
      self.pole = pole_structure_mapper.msg.PoleSection()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_6d2f.pack(_x.pole.base.x, _x.pole.base.y, _x.pole.base.z, _x.pole.axis.x, _x.pole.axis.y, _x.pole.axis.z, _x.pole.diameter, _x.pole.length))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      if self.pole is None:
        self.pole = pole_structure_mapper.msg.PoleSection()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.pole.base.x, _x.pole.base.y, _x.pole.base.z, _x.pole.axis.x, _x.pole.axis.y, _x.pole.axis.z, _x.pole.diameter, _x.pole.length,) = _struct_6d2f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_6d2f.pack(_x.pole.base.x, _x.pole.base.y, _x.pole.base.z, _x.pole.axis.x, _x.pole.axis.y, _x.pole.axis.z, _x.pole.diameter, _x.pole.length))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      if self.pole is None:
        self.pole = pole_structure_mapper.msg.PoleSection()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.pole.base.x, _x.pole.base.y, _x.pole.base.z, _x.pole.axis.x, _x.pole.axis.y, _x.pole.axis.z, _x.pole.diameter, _x.pole.length,) = _struct_6d2f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_3I = struct.Struct("<3I")
_struct_6d2f = struct.Struct("<6d2f")
