/* Auto-generated by genmsg_cpp for file /home/blazz/myStacks/lse_battery_drivers/laptop_battery/msg/Battery.msg */
#ifndef LAPTOP_BATTERY_MESSAGE_BATTERY_H
#define LAPTOP_BATTERY_MESSAGE_BATTERY_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "roslib/Header.h"

namespace laptop_battery
{
template <class ContainerAllocator>
struct Battery_ : public ros::Message
{
  typedef Battery_<ContainerAllocator> Type;

  Battery_()
  : header()
  , charging(false)
  , level(0.0)
  , time_remaining(0)
  {
  }

  Battery_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , charging(false)
  , level(0.0)
  , time_remaining(0)
  {
  }

  typedef  ::roslib::Header_<ContainerAllocator>  _header_type;
   ::roslib::Header_<ContainerAllocator>  header;

  typedef uint8_t _charging_type;
  uint8_t charging;

  typedef float _level_type;
  float level;

  typedef uint32_t _time_remaining_type;
  uint32_t time_remaining;


private:
  static const char* __s_getDataType_() { return "laptop_battery/Battery"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "21f54717ee47fec662ccdb9a6ca81a7d"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
bool charging\n\
float32 level				# in %\n\
uint32 time_remaining		# in minutes\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, charging);
    ros::serialization::serialize(stream, level);
    ros::serialization::serialize(stream, time_remaining);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, charging);
    ros::serialization::deserialize(stream, level);
    ros::serialization::deserialize(stream, time_remaining);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(charging);
    size += ros::serialization::serializationLength(level);
    size += ros::serialization::serializationLength(time_remaining);
    return size;
  }

  typedef boost::shared_ptr< ::laptop_battery::Battery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laptop_battery::Battery_<ContainerAllocator>  const> ConstPtr;
}; // struct Battery
typedef  ::laptop_battery::Battery_<std::allocator<void> > Battery;

typedef boost::shared_ptr< ::laptop_battery::Battery> BatteryPtr;
typedef boost::shared_ptr< ::laptop_battery::Battery const> BatteryConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::laptop_battery::Battery_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::laptop_battery::Battery_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace laptop_battery

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::laptop_battery::Battery_<ContainerAllocator> > {
  static const char* value() 
  {
    return "21f54717ee47fec662ccdb9a6ca81a7d";
  }

  static const char* value(const  ::laptop_battery::Battery_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x21f54717ee47fec6ULL;
  static const uint64_t static_value2 = 0x62ccdb9a6ca81a7dULL;
};

template<class ContainerAllocator>
struct DataType< ::laptop_battery::Battery_<ContainerAllocator> > {
  static const char* value() 
  {
    return "laptop_battery/Battery";
  }

  static const char* value(const  ::laptop_battery::Battery_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::laptop_battery::Battery_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
bool charging\n\
float32 level				# in %\n\
uint32 time_remaining		# in minutes\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::laptop_battery::Battery_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::laptop_battery::Battery_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::laptop_battery::Battery_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.charging);
    stream.next(m.level);
    stream.next(m.time_remaining);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Battery_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laptop_battery::Battery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::laptop_battery::Battery_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::roslib::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "charging: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.charging);
    s << indent << "level: ";
    Printer<float>::stream(s, indent + "  ", v.level);
    s << indent << "time_remaining: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time_remaining);
  }
};


} // namespace message_operations
} // namespace ros

#endif // LAPTOP_BATTERY_MESSAGE_BATTERY_H

